---
platform: linux
inputs:
  - name: repo
params:
  RT_URL: "https://crl.jfrog.io/artifactory"
run:
  dir: repo/src
  path: /bin/bash 
  args:
    - -c
    - |
      VERSION=$(cat VERSION)
      jfrog rt c rt-server -url $RT_URL --user ((writer-artifactory-user)) --password ((writer-artifactory-token)) --interactive=false
      jfrog rt gp devops-go-local $VERSION --server-id rt-server
