---
platform: linux
inputs:
  - name: repo
params:
  RT_URL: "https://crl.jfrog.io/artifactory"
run:
  dir: repo/src
  path: /bin/bash 
  args:
    - -c
    - |
      VERSION=$(cat VERSION)
      jf c add --access-token=((writer-artifactory-token)) --artifactory-url=$RT_URL --interactive=false artifactory
      jf goc --server-id-resolve artifactory --server-id-deploy artifactory --repo-resolve go --repo-deploy devops-go-local
      jf gp $VERSION 
