---
yaml_anchors:
  git-token: &git-token
    username: x-oauth-basic
    password: ((carnegierobotics-access-token))
    git_config:
      - name: "url.https://x-oauth-basic:((carnegierobotics-access-token))@github.com/.insteadOf"
        value: "git@github.com:"
  job-config: &job-config
    build_log_retention: &build-log-retention
      builds: 10
      minimum_succeeded_builds: 3
  step-config: &step-config
    tags: [on-prem]
resources:
  - name: repo
    type: git
    icon: git
    source:
      uri: git@github.com:carnegierobotics/greenhouse-client-go.git 
      branch: ((project-branch))
      <<: *git-token 
    <<: *step-config
  - name: jfrog-cli-image
    type: registry-image
    icon: docker 
    check_every: never
    source:
      repository: releases-docker.jfrog.io/jfrog/jfrog-cli-full-v2-jf 
      tag: latest
      #username: ((writer-artifactory-user))
      #password: ((writer-artifactory-token))
    <<: *step-config
jobs:
  - name: apply-template
    old_name: apply-template
    plan:
      - get: repo 
        trigger: true
        <<: *step-config
      - set_pipeline: self
        file: repo/ci/pipeline.yml
        var_files: 
          - repo/ci/vars.yml
  - name: build
    <<: *job-config
    plan:
      - get: repo
        trigger: true
        <<: *step-config
        passed: [apply-template]
      - get: jfrog-cli-image
        trigger: false
        <<: *step-config
      - task: build
        privileged: false 
        file: repo/ci/tasks/build.yml
        image: jfrog-cli-image
        input_mapping:
          repo: repo 
        <<: *step-config
